language: csharp
mono: none
dotnet: 1.1.2

solution: DeveMazeGenerator.sln

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      env: CONFIGURATION=Release
      services:
        - docker
    - os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Debug
    - os: osx
      osx_image: xcode8.2 # macOS 10.11
      env: CONFIGURATION=Release
    - os: osx
      osx_image: xcode8.2
      env: CONFIGURATION=Debug



notifications:
  email: false