# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

env:
  HEROKU_API_KEY:
    secure: pUcQGovSmYBCpc1cUI5mlN3hqETqrknOqIQT3F/T9QGf5thpnrbLn7qp/NrO5Bm6JXji6RJflX4E4HTcbZLlqiv+yZRPHcPTesmcpyGh4B4TvVZdLE+05b4l4aDoBNIiR8tJfe/RDPWd3Qplrji6dfqwX45pJ3d6QuMvrtyxAKq6rGJJZjvbVy9Zx7JPxz2R4XoGuG1GCwEQoml7P6s9CzW00CkHqY6kMSjFJh4xuP0OOBKbZ3IcJJvMbQemqqdd7SXrQzzu78oyLA+OpKpzXFqEyHjU+3qiZc1t7qIDFGp3jSctOTXC49kpaRzoXKXujyq9cpcpyuHeG2/jIkh6JwtehDe+w1F6t8DNDeh+frZpMECJwtcjrhs5VxSq6Jim26YxFgmkbq3uFE0kqgjvRKaA20+q9wXpeEHv4Pu/lDkHHbsk98IfugYxBfpWxmqCVY6tD0UyvCchFIB2WLJ1bTvfZvY1IJ+jIc0NHUxJMXK6VIpGN9ugE9NTN7ZlX3pwmMwJM8fYkTteyXnjCJin3DFkEWqtyH11PkBO8w0GU/vVn1b1IrkiALotw77ykUzwHXCi5s1fK810D2G69PfGemSH24MM01QDw7eDlD8f/ifjMnb5tDiNjudtVjwr1OAAgvCS6He6bReOlsAuKCUPJzjMahxOcntQEHusVHot1iM=

branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: trusty # Ubuntu 14.04

script:
  - docker build -t devedse/devemazegeneratorcore:latest .;
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker image tag devedse/devemazegeneratorcore:latest "devedse/devemazegeneratorcore:$TRAVIS_BUILD_NUMBER";
      docker images;
      docker push devedse/devemazegeneratorcore;
    fi
  - heroku container:login;
  - docker image tag devedse/devemazegeneratorcore:latest "registry.heroku.com/devemazegeneratorcore/latest";
  - heroku container:push devedse/devemazegeneratorcore --app devemazegeneratorcore
  - heroku container:release devedse/devemazegeneratorcore --app devemazegeneratorcore

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: C2fV48hOJAXouP2EMaYmh9XiFI/LFnxmjBmLoWV/SByjPEdenjxYtQYKp83AfvH/KSGJR+V+eAfNZEZ7z7eAt8wOPnRnjcI+JrUmvyfF/d+wnCRe18xUYyyzrT0q9SyYyMLZIi54dMZx0+qdgSknacvXFQd+h96IOo98Sb4/XibpTtGlqKR7KLTSy6pqjv51E+7DV9SaacOG7jCEsD8KJbSx6WUg4hDoCA560VhpCg/nk3PAiDkqaQZULalTXcEjeJNkfl1hy6B0wVHpAVmc6+WxOFuRu2AmsLiPdB6nM8xmVP8rRZPy8G7MWAjr8EJK3M+lybE8EtLXkAolvsWEuKfqMIm/2JJfNOpwWTdGlxGLDUzVFKSaGt7aZK4gdICtB321Dfe1rWL3mAWnqbl75N8QRL/Y4yaFMcLsRNHtGk56HYaXV2rCEgW+Ag+Jhwn5fBvFpXSTWO+MC5rpdbBV6gYSIMNfORU+r9ylZsvIO4wrag5DESOGI4Jbpz06Ldql6VkxIpwXM1G6JjI7BZTyjVrHjr6n4ezmah9vLiD5EvS+egyEx9BW3c7z7inlxZMZPgrKTStbzorJ9FaVuexMfdmQJ2/co0nlvKsxIWIARjDsv+JGyNk7qKW9HdeKCaO7hXJFSpj98EsFBWP8Nc6ZFcUeRN9DE6aCiyEePx2ZrOs=
  app: devemazegeneratorcore
  run:
    - "docker ps"
    - restart

