language: csharp
solution: DeveMazeGenerator.sln

branches:
  only:
  - master

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
      os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      env: CONFIGURATION=Release
      services:
        - docker
    - dotnet: 1.0.4
      mono: none
      os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Debug
    - dotnet: 1.0.4
      mono: none
      os: osx
      osx_image: xcode8.2 # macOS 10.11
      env: CONFIGURATION=Release
    - dotnet: 1.0.4
      mono: none
      os: osx
      osx_image: xcode8.2
      env: CONFIGURATION=Debug

script:
  - dotnet restore

notifications:
  email: false