language: csharp
solution: DeveMazeGenerator.sln

branches:
  only:
  - master

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
      os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      env: CONFIGURATION=Release
      services:
        - docker
    - dotnet: 1.0.4
      mono: none
      os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Debug
    - dotnet: 1.0.4
      mono: none
      os: osx
      osx_image: xcode8.2 # macOS 10.11
      env: CONFIGURATION=Release
    - dotnet: 1.0.4
      mono: none
      os: osx
      osx_image: xcode8.2
      env: CONFIGURATION=Debug

before_script:
  - dotnet restore

script:
  - dotnet build -c $CONFIGURATION
  - dotnet test -c $CONFIGURATION ./test/DeveMazeGenerator.Tests/DeveMazeGenerator.Tests.csproj
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIGURATION" == "Release" ]]; then
      mkdir ./Scripts/Docker/DeveMazeGeneratorCoreWebPublish;
      dotnet publish -c $CONFIGURATION ./src/DeveMazeGeneratorWeb/ --output ./Scripts/Docker/DeveMazeGeneratorCoreWebPublish;
      cd Scripts;
      cd Docker;
      docker build -t devedse/devemazegeneratorcore .;
      cd ..;
      cd ..;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push devedse/devemazegeneratorcore:latest;
    fi

notifications:
  email: false