# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: trusty # Ubuntu 14.04

script:
  - docker build -t devedse/devemazegeneratorcore .;
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push devedse/devemazegeneratorcore:latest;
    fi

notifications:
  email: false