# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: trusty # Ubuntu 14.04

script:
  - docker build -t devedse/devemazegeneratorcore:latest .;
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker image tag devedse/devemazegeneratorcore:latest "devedse/devemazegeneratorcore:$TRAVIS_BUILD_NUMBER";
      docker images;
      docker push devedse/devemazegeneratorcore;
    fi

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: C2fV48hOJAXouP2EMaYmh9XiFI/LFnxmjBmLoWV/SByjPEdenjxYtQYKp83AfvH/KSGJR+V+eAfNZEZ7z7eAt8wOPnRnjcI+JrUmvyfF/d+wnCRe18xUYyyzrT0q9SyYyMLZIi54dMZx0+qdgSknacvXFQd+h96IOo98Sb4/XibpTtGlqKR7KLTSy6pqjv51E+7DV9SaacOG7jCEsD8KJbSx6WUg4hDoCA560VhpCg/nk3PAiDkqaQZULalTXcEjeJNkfl1hy6B0wVHpAVmc6+WxOFuRu2AmsLiPdB6nM8xmVP8rRZPy8G7MWAjr8EJK3M+lybE8EtLXkAolvsWEuKfqMIm/2JJfNOpwWTdGlxGLDUzVFKSaGt7aZK4gdICtB321Dfe1rWL3mAWnqbl75N8QRL/Y4yaFMcLsRNHtGk56HYaXV2rCEgW+Ag+Jhwn5fBvFpXSTWO+MC5rpdbBV6gYSIMNfORU+r9ylZsvIO4wrag5DESOGI4Jbpz06Ldql6VkxIpwXM1G6JjI7BZTyjVrHjr6n4ezmah9vLiD5EvS+egyEx9BW3c7z7inlxZMZPgrKTStbzorJ9FaVuexMfdmQJ2/co0nlvKsxIWIARjDsv+JGyNk7qKW9HdeKCaO7hXJFSpj98EsFBWP8Nc6ZFcUeRN9DE6aCiyEePx2ZrOs=
  app: devemazegeneratorcore
  run:
    - "docker ps"
    - restart

