version: 1.0.{build}
os: Visual Studio 2019
skip_tags: true
configuration: Release

environment:
  sonarqubetoken:
    secure: ppdeirHI9dsM7NpQgtwIRqXbiqhJZvIyHxOFhnME5HhRFS6IbYZqRppQi7fTqv37

before_build:
  #- ps: .\scripts\set-version.ps1
  - dotnet --info
  - dotnet tool install --global dotnet-reportgenerator-globaltool
  #- choco install opencover.portable
  - choco install codecov
  #- choco install xunit
  - choco install "msbuild-sonarqube-runner" -y
  - choco install 7zip

build_script:
  - SonarScanner.MSBuild.exe begin /k:"DeveMazeGeneratorCore" /o:"devedse-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%sonarqubetoken% /d:sonar.cs.opencover.reportsPaths=".\DeveMazeGeneratorCore.Tests\TestResults\Coverage\coverage.opencover.xml" /d:sonar.coverage.exclusions="DeveMazeGeneratorCore.ConsoleApp/**/*.cs,DeveMazeGeneratorCore.Tests/**/*.cs"
  - dotnet build DeveMazeGeneratorCore.sln -c Release /p:Version=%APPVEYOR_BUILD_VERSION%
  #- OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\DeveMazeGeneratorCore.Tests\DeveMazeGeneratorCore.Tests.csproj -c Release" -oldstyle -returntargetcode -output:.\DeveMazeGeneratorCore.Coverage.xml -filter:"+[DeveMazeGeneratorCore*]*"
  - dotnet test DeveMazeGeneratorCore.sln --no-build -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\" /p:CoverletOutput=./TestResults/Coverage/
  - SonarScanner.MSBuild.exe end /d:sonar.login=%sonarqubetoken%
  - codecov -f ".\DeveMazeGeneratorCore.Tests\TestResults\Coverage\coverage.opencover.xml"
  - reportgenerator -reports:.\DeveMazeGeneratorCore.Tests\TestResults\Coverage\coverage.opencover.xml -targetdir:.\DeveMazeGeneratorCore.Tests\TestResults\Coverage\HtmlInline\ -reporttypes:HtmlInline_AzurePipelines
 
after_test:
  - dotnet pack -c Release DeveMazeGeneratorCore\DeveMazeGeneratorCore.csproj
  - ps: Scripts\GoPackage.ps1
  - 7z a -t7z -m0=LZMA2 -mmt=on -mx9 -md=1536m -mfb=273 -ms=on -mqs=on -sccUTF-8 "Scripts\Output\CodeCoverageReport.7z" ".\DeveMazeGeneratorCore.Tests\TestResults\Coverage\HtmlInline\*"

artifacts:
- path: Scripts\Output\DeveMazeGeneratorCore.7z
  name: droppackage7z
- path: Scripts\Output\DeveMazeGeneratorCore.zip
  name: droppackagezip
- path: 'DeveMazeGeneratorCore\bin\Release\*.nupkg'
  name: nugetPackages
- path: 'DeveMazeGeneratorCore\bin\Release\*.snupkg'
  name: snugetPackages
- path: Scripts\Output\CodeCoverageReport.7z
  name: CodeCoverageReport

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: droppackage7z,droppackagezip,nugetPackages,snugetPackages
- provider: NuGet
  api_key:
    secure: pVOzQthQbu7P9SUQwjG43ZEMcwAp7dVbe4BkDVEwJFu1gWK+L11L9mdfGLC5iO5Z