version: '3.4'

services:
  devemazegeneratorcore.web:
    image: ${DOCKER_REGISTRY-}devemazegeneratorcoreweb
    build:
      context: .
      dockerfile: DeveMazeGeneratorCore.Web/Dockerfile
      args:
        - BUILD_VERSION=${TRAVIS_BUILD_NUMBER}

  devemazegeneratorcore.web.arm64:
    image: ${DOCKER_REGISTRY-}devemazegeneratorcorewebarm64
    build:
      context: .
      dockerfile: DeveMazeGeneratorCore.Web/ARM64.Dockerfile
      args:
        - BUILD_VERSION=${TRAVIS_BUILD_NUMBER}

  devemazegeneratorcore.web.arm32:
    image: ${DOCKER_REGISTRY-}devemazegeneratorcorewebarm32
    build:
      context: .
      dockerfile: DeveMazeGeneratorCore.Web/ARM32.Dockerfile
      args:
        - BUILD_VERSION=${TRAVIS_BUILD_NUMBER}

  devemazegeneratorcore.consoleapp:
    image: ${DOCKER_REGISTRY-}devemazegeneratorcoreconsoleapp
    build:
      context: .
      dockerfile: DeveMazeGeneratorCore.ConsoleApp/Dockerfile
      args:
        - BUILD_VERSION=${TRAVIS_BUILD_NUMBER}