# The stuff that actually matters.
#
# What we want to be able to do is go directly from the state of our
# neighbours and an RNG value to the location delta and the direction pointing
# back to the start.
#
# There are 16 possible states of our neighbours (4 bits, each representing 
# if that direction is occupied). For each of those possible states we will
# store a mapping from RNG to direction.  We need to handle having 1 2 or 3
# possible neighbours, so we actually use least common multiple (6).  This means
# we arent distorting the distribution.
#
# Rather than packing things as close as possible we align the table to
# multiples of 8, with the last 2 slots being invalid - never to be generated by
# the RNG.  We do this because to generate the offset into a flattened lookup
# table we need to multiply the neigbour mask by the number of choices.  If we
# packed everything tight this would be *6, but for a tiny bit of wasted space
# this becomes a *8 which can be implemented with a bit shift.
#
# At the index of the combined neighbour state and RNG value we store the chosen
# direction as a nibble (1 = UP, 2 = RIGHT, 4 = DOWN, 8 = LEFT, no valid
# direction is 0). Storing it like this allows us to directly index into the
# DX and DY value (or the reverse when we are tracing back to the start) while
# also handling dead ends.  Since no valid direction is zero we detect a dead
# end with a "branch if zero" which has its own efficient op in many
# architectures.  Obviously it is not so impactful in python, but this code is
# just for illustration.
#
# The lookup table is tiny and should almost certainly remain in whatever the
# lowest cache level is.
import random

# Translation arrays: Convert the direction back to the start into a forward-move
# delta.
DX = [0,  0, -1,  0,  0,  0,  0,  0,  1]
DY = [0,  1,  0,  0, -1,  0,  0,  0,  0]

# The inverse of the delta - Given a maze with the direction give the offset to
# the previous cell. Just DX and DY * -1.
TRACE_DX = [0, 0, 1, 0, 0, 0, 0, 0, -1]
TRACE_DY = [0, -1, 0, 0, 1, 0, 0, 0, 0]


def generate_back_bits_table():
    # The opposite of going up (1) is down (4), etc.  Only used for generating
    # the lookup table so a map is fine here.
    REVERSE = {1: 4, 2: 8, 4: 1, 8: 2}
    table = [0] * 128
    for mask in range(16):
        valid_bits = [b for b in [1, 2, 4, 8] if (mask & b)]
        if not valid_bits: continue
        base, num_valid = mask << 3, len(valid_bits)
        repeats = 6 // num_valid if num_valid <= 3 else 1
        choices = []
        for b in valid_bits: choices.extend([REVERSE[b]] * repeats)
        for i in range(min(6, len(choices))): table[base + i] = choices[i]
    return table

BACK_BITS_TABLE = generate_back_bits_table()

def move_randomly(maze, x, y):
    # This is the code we have optimised the hell out of because it runs
    # every step.
    #   - RNG does not depend on the number of neighbours.
    #   - Only a single bitshift and add to compute the next cell and
    #     the direction back towards the start.
    mask = maze.get_passable_map(x, y)
    idx = (mask << 3) + random.randrange(6)
    back_bits = BACK_BITS_TABLE[idx]
    return x + DX[back_bits], y + DY[back_bits], back_bits




# Placeholder maze implementation - not optimised for storage or speed.
# All following code is AI generated - dont hate me, it works and that
# is good enough to prove the technique is viable.


class Maze:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        # grid[y][x] stores the bitmask pointing toward the start. 0 = unvisited.
        self.grid = [[0 for _ in range(width)] for _ in range(height)]

    def get_passable_map(self, x, y):
        """
        Returns a 4-bit mask of neighbors that are inside bounds AND unvisited.
        This could be a lot more efficient.
        """
        mask = 0
        if y > 0 and self.grid[y-1][x] == 0: mask |= 1 # UP
        if x < self.width - 1 and self.grid[y][x+1] == 0: mask |= 2 # RIGHT
        if y < self.height - 1 and self.grid[y+1][x] == 0: mask |= 4 # DOWN
        if x > 0 and self.grid[y][x-1] == 0: mask |= 8 # LEFT
        return mask

    def set_back_direction(self, x, y, bit):
        self.grid[y][x] = bit

def generate_maze(width, height):
    maze = Maze(width, height)
    # Start at 0,0. Sentinel 15 marks the root.
    maze.grid[0][0] = 15 
    stack = [(0, 0)]
    while stack:
        x, y = stack[-1]
        mask = maze.get_passable_map(x, y)
        back_bits = BACK_BITS_TABLE[(mask << 3) + random.randrange(6)]
        if back_bits == 0:
            stack.pop()
        else:
            nx, ny = x + DX[back_bits], y + DY[back_bits]
            maze.grid[ny][nx] = back_bits
            stack.append((nx, ny))
    return maze

def solve_path(maze, end_x, end_y):
    path = set()
    cx, cy = end_x, end_y
    while maze.grid[cy][cx] != 15:
        path.add((cx, cy))
        b = maze.grid[cy][cx]
        cx += TRACE_DX[b]
        cy += TRACE_DY[b]
    path.add((cx, cy))
    return path

def draw_maze_with_walls(maze, path):
    # Expand the grid: each cell is 2x2 in the output
    render_w = maze.width * 2 + 1
    render_h = maze.height * 2 + 1
    
    # Initialize everything as a wall
    output = [["█" for _ in range(render_w)] for _ in range(render_h)]

    for y in range(maze.height):
        for x in range(maze.width):
            # Center of the cell in the expanded grid
            rx, ry = x * 2 + 1, y * 2 + 1
            
            # Open the cell itself
            output[ry][rx] = "·" if (x, y) in path else " "
            
            # Check the back-pointer to open a passage to the neighbor
            b = maze.grid[y][x]
            if b == 1: output[ry-1][rx] = " " # Passage UP
            if b == 2: output[ry][rx+1] = " " # Passage RIGHT
            if b == 4: output[ry+1][rx] = " " # Passage DOWN
            if b == 8: output[ry][rx-1] = " " # Passage LEFT

    # Print the resulting character grid
    for row in output:
        print("".join(row))

if __name__ == "__main__":
    W, H = 30, 15
    m = generate_maze(W, H)
    p = solve_path(m, W-1, H-1)
    draw_maze_with_walls(m, p)
