<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<KniPlatform>BlazorGL</KniPlatform>
	</PropertyGroup>

	<PropertyGroup>
		<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants)TRACE;OPENGL;BLAZOR</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants)TRACE;OPENGL;BLAZOR</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<KniContentReference Include="..\DeveMazeGeneratorCore.MonoGame.Content\Content\Content.mgcb">
			<Link>Content\Content.mgcb</Link>
		</KniContentReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.32" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.32" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.17" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.17" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="nkast.Kni.Platform.Blazor.GL" Version="4.2.9001.2" />
		<PackageReference Include="nkast.Xna.Framework.Content.Pipeline.Builder" Version="4.2.9001" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeveMazeGeneratorCore.MonoGame.Core\DeveMazeGeneratorCore.MonoGame.Core.csproj" />
	</ItemGroup>

</Project>